<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Product Profit Analysis – Vasif Asadov | AdventureWorks Bike Sales Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0cda25dcbb8fe09c7138904322940710.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-095c5612e4422d114998b098e0e10f6c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Vasif Asadov | AdventureWorks Bike Sales Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">AdventureWorks Bike Sales</li><li class="breadcrumb-item"><a href="./04_performance_analysis.html">Product Profit Analysis</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">AdventureWorks Bike Sales</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
 <span class="menu-text">00_problem_description.qmd</span>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_data_preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Preparation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_macro_performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Macro Performance Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_customer_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Customer Segmentation Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_performance_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Product Profit Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_sales_reasons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sales Reasons Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_regional_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regional Sales Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_executive_dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive Dashboard</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#product-profit-analysis" id="toc-product-profit-analysis" class="nav-link" data-scroll-target="#product-profit-analysis">Product Profit Analysis</a>
  <ul class="collapse">
  <li><a href="#profit-margin-analysis" id="toc-profit-margin-analysis" class="nav-link" data-scroll-target="#profit-margin-analysis">Profit Margin Analysis</a></li>
  <li><a href="#high-volume-vs-high-value-products" id="toc-high-volume-vs-high-value-products" class="nav-link" data-scroll-target="#high-volume-vs-high-value-products">High Volume vs High Value Products</a></li>
  <li><a href="#basket-size-analysis" id="toc-basket-size-analysis" class="nav-link" data-scroll-target="#basket-size-analysis">Basket Size Analysis</a></li>
  <li><a href="#dead-weight-products" id="toc-dead-weight-products" class="nav-link" data-scroll-target="#dead-weight-products">Dead Weight Products</a></li>
  <li><a href="#product-pricing-tiers-effect" id="toc-product-pricing-tiers-effect" class="nav-link" data-scroll-target="#product-pricing-tiers-effect">Product Pricing Tiers Effect</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">AdventureWorks Bike Sales</li><li class="breadcrumb-item"><a href="./04_performance_analysis.html">Product Profit Analysis</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Product Profit Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This section focuses on analyzing the profitability of our product offerings. We will explore various dimensions of product performance, including profit margins, sales volume, and customer purchasing behavior. This will allow us to identify which products are driving profitability and which may be underperforming and which are dead weight products. That information will be crucial for making informed decisions about inventory management, marketing strategies, and product development.</p>
</section>
<section id="product-profit-analysis" class="level1">
<h1>Product Profit Analysis</h1>
<section id="profit-margin-analysis" class="level2">
<h2 class="anchored" data-anchor-id="profit-margin-analysis">Profit Margin Analysis</h2>
<p><code>11. Which product categories and subcategories drive the highest profit margins, and which are drag on profitability?</code></p>
<p><strong>Solution:</strong> Solving this questions will reveal which product categories and subcategories are the most profitable and which are underperforming. So, we need to calculate financial metrics first, and then group the results by product category and subcategory to identify trends and insights. The following SQL query calculates total revenue, total cost, total profit, and profit margin for each product category and subcategory. Note: When the financial metrics are calculated, there may be some categories or subcategories with no sales, which would lead to null values. To handle this effectively without corrupting the analysis, we can use the <code>COALESCE</code> function to replace null values with zeros. This ensures that our calculations for profit and profit margin are accurate and that we can still include those categories in our analysis without skewing the results.</p>
<details>
<summary>
Show SQL Code
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">with</span> product_stats <span class="kw">as</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">select</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>        sub.ProductSubcategoryName <span class="kw">as</span> product_subcategory, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        cat.ProductCategoryName <span class="kw">as</span> product_category,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">cast</span>(<span class="fu">sum</span>(fis.salesamount) <span class="kw">as</span> <span class="dt">decimal</span>(<span class="dv">20</span>,<span class="dv">3</span>)) <span class="kw">as</span> total_revenue,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">cast</span>(<span class="fu">sum</span>(fis.totalproductcost) <span class="kw">as</span> <span class="dt">decimal</span>(<span class="dv">20</span>,<span class="dv">3</span>)) <span class="kw">as</span> total_cost</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">from</span> Products p</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">left</span> <span class="kw">join</span> FactInternetSales fis</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>        <span class="kw">on</span> fis.ProductKey <span class="op">=</span> p.ProductKey</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">inner</span> <span class="kw">join</span> ProductSubcategory sub</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        <span class="kw">on</span> p.ProductSubcategoryKey <span class="op">=</span> sub.ProductSubcategoryKey</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">inner</span> <span class="kw">join</span> ProductCategory cat</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        <span class="kw">on</span> sub.ProductCategoryKey <span class="op">=</span> cat.ProductCategoryKey</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">group</span> <span class="kw">by</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>        sub.ProductSubcategoryName, </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        cat.ProductCategoryName</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    product_category,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    product_subcategory,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(total_revenue,<span class="dv">0</span>) <span class="kw">as</span> total_revenue,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(total_cost,<span class="dv">0</span>) <span class="kw">as</span> total_cost,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(total_revenue <span class="op">-</span> total_cost,<span class="dv">0</span>) <span class="kw">as</span> total_profit,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">cast</span>(<span class="fl">100.0</span> <span class="op">*</span> (total_revenue <span class="op">-</span> total_cost) <span class="op">/</span> </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        <span class="fu">nullif</span>(total_revenue,<span class="dv">0</span>) <span class="kw">as</span> <span class="dt">decimal</span>(<span class="dv">10</span>,<span class="dv">3</span>)),<span class="dv">0</span>) <span class="kw">as</span> profit_margin</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> product_stats</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="kw">by</span> </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    profit_margin <span class="kw">desc</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>product_category</th>
<th>product_subcategory</th>
<th>total_revenue</th>
<th>total_cost</th>
<th>total_profit</th>
<th>profit_margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accessories</td>
<td>Bike Racks</td>
<td>39360.000</td>
<td>14720.640</td>
<td>24639.360</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Accessories</td>
<td>Bike Stands</td>
<td>39591.000</td>
<td>14807.034</td>
<td>24783.966</td>
<td>62.600</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Tires and Tubes</td>
<td>245529.320</td>
<td>91828.569</td>
<td>153700.751</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Accessories</td>
<td>Cleaners</td>
<td>7218.600</td>
<td>2699.756</td>
<td>4518.844</td>
<td>62.600</td>
</tr>
<tr class="odd">
<td>Clothing</td>
<td>Shorts</td>
<td>71319.810</td>
<td>26673.650</td>
<td>44646.160</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Clothing</td>
<td>Vests</td>
<td>35687.000</td>
<td>13346.938</td>
<td>22340.062</td>
<td>62.600</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Hydration Packs</td>
<td>40307.670</td>
<td>15075.098</td>
<td>25232.572</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Accessories</td>
<td>Helmets</td>
<td>225335.600</td>
<td>84275.772</td>
<td>141059.828</td>
<td>62.600</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Fenders</td>
<td>46619.580</td>
<td>17435.681</td>
<td>29183.899</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Clothing</td>
<td>Gloves</td>
<td>35020.700</td>
<td>13097.799</td>
<td>21922.901</td>
<td>62.600</td>
</tr>
<tr class="odd">
<td>Clothing</td>
<td>Socks</td>
<td>5106.320</td>
<td>1909.786</td>
<td>3196.534</td>
<td>62.600</td>
</tr>
<tr class="even">
<td>Accessories</td>
<td>Bottles and Cages</td>
<td>56798.190</td>
<td>21242.842</td>
<td>35555.348</td>
<td>62.599</td>
</tr>
<tr class="odd">
<td>Bikes</td>
<td>Mountain Bikes</td>
<td>9952759.564</td>
<td>5439135.458</td>
<td>4513624.106</td>
<td>45.350</td>
</tr>
<tr class="even">
<td>Bikes</td>
<td>Road Bikes</td>
<td>14520584.036</td>
<td>8983284.338</td>
<td>5537299.698</td>
<td>38.134</td>
</tr>
<tr class="odd">
<td>Bikes</td>
<td>Touring Bikes</td>
<td>3844801.050</td>
<td>2389928.354</td>
<td>1454872.696</td>
<td>37.840</td>
</tr>
<tr class="even">
<td>Clothing</td>
<td>Caps</td>
<td>19688.100</td>
<td>15159.837</td>
<td>4528.263</td>
<td>23.000</td>
</tr>
<tr class="odd">
<td>Clothing</td>
<td>Jerseys</td>
<td>172950.680</td>
<td>133172.024</td>
<td>39778.656</td>
<td>23.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Headsets</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Chains</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Pedals</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Cranksets</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Bottom Brackets</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Mountain Frames</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Derailleurs</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Locks</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Handlebars</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Panniers</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Accessories</td>
<td>Pumps</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Forks</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Clothing</td>
<td>Bib-Shorts</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Wheels</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Brakes</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Clothing</td>
<td>Tights</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Road Frames</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Components</td>
<td>Saddles</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Components</td>
<td>Touring Frames</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Accessories</td>
<td>Lights</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
</tr>
</tbody>
</table>
<p><strong>Insights:</strong> The analysis revealed the following insights:</p>
<ul>
<li>The “Accessories” category, particularly subcategories like “Bike Racks,” “Bike Stands,” and “Tires and Tubes,” consistently showed high profit margins, indicating strong profitability in these areas.</li>
<li>The “Clothing” category also demonstrated solid profit margins, with subcategories such as “Shorts” and “Vests” performing well.</li>
<li>In contrast, the “Bikes” category, while generating significant total profit, had lower profit margins compared to accessories and clothing, suggesting that the cost structure for bikes may be less favorable.</li>
<li>The “Components” category had no recorded sales, resulting in zero profit and profit margin, which indicates that these products may not be contributing to profitability and could be considered for reevaluation in the product lineup. Don’t forget that the highest profit margin does not mean the highest total profit. For example, the “Bikes” category has a lower profit margin than “Accessories,” but it generates a much higher total profit due to its larger sales volume. This highlights the importance of considering both profit margin and total profit when evaluating product performance. Profit margin just illustrates the difference between revenue and cost, while total profit takes into account the scale of sales, which can significantly impact overall profitability. Therefore, it’s crucial to analyze both metrics to get a comprehensive understanding of product performance and make informed decisions about inventory management and marketing strategies.</li>
</ul>
</section>
<section id="high-volume-vs-high-value-products" class="level2">
<h2 class="anchored" data-anchor-id="high-volume-vs-high-value-products">High Volume vs High Value Products</h2>
<p><code>12. What is the disparity between our "High Volume" products and our "High Value" products?</code></p>
<p><strong>Solution:</strong> To solve this question, we need to give a rank to our products based on their <em>Value</em> - total revenue coming from the product, and <em>Volume</em> - total quantity sold for that product. Then we can compare the top 10 products in each category to see if there are any disparities between high volume and high value products. If the volume rank is significantly different from the value rank, it means that the product is either a high volume product with low value or a high value product with low volume. The main strategy of the companies is mainly getting higher revenue. Therefore, in this analysis, we mainly focus on the high value products and try to increase the volume size of those products. However, we also need to keep an eye on the high volume products, as they can also contribute significantly to total revenue, even if their profit margins are lower. By analyzing the disparity between high volume and high value products, we can identify opportunities to optimize our product offerings and marketing strategies to maximize profitability.</p>
<details>
<summary>
Show SQL Code
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">with</span> product_agg <span class="kw">as</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">select</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        p.ProductKey,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        p.ProductName,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(salesamount) <span class="kw">as</span> product_revenue, </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(OrderQuantity) <span class="kw">as</span> product_quantity </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">from</span> FactInternetSales fis</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">join</span> products p</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        <span class="kw">on</span> p.ProductKey <span class="op">=</span> fis.ProductKey</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">group</span> <span class="kw">by</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        p.ProductKey,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        p.ProductName</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>rank_products <span class="kw">as</span> (</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">select</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        ProductName,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        product_revenue,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        product_quantity,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">row_number</span>() <span class="kw">over</span> (<span class="kw">order</span> <span class="kw">by</span> product_revenue <span class="kw">desc</span>) <span class="kw">as</span> product_value_rank,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>        <span class="fu">row_number</span>() <span class="kw">over</span> (<span class="kw">order</span> <span class="kw">by</span> product_quantity <span class="kw">desc</span>) <span class="kw">as</span> product_volume_rank</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="kw">from</span> product_agg</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    ProductName,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    product_revenue,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    product_quantity,</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    product_value_rank,</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    product_volume_rank</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> rank_products</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="kw">where</span> product_value_rank <span class="op">&lt;=</span> <span class="dv">10</span> <span class="kw">or</span> product_volume_rank <span class="op">&lt;=</span> <span class="dv">10</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="kw">by</span> product_value_rank <span class="kw">asc</span>, product_volume_rank;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>ProductName</th>
<th>product_revenue</th>
<th>product_quantity</th>
<th>product_value_rank</th>
<th>product_volume_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Road-150 Red, 48</td>
<td>1205876.9900</td>
<td>337</td>
<td>1</td>
<td>44</td>
</tr>
<tr class="even">
<td>Road-150 Red, 62</td>
<td>1202298.7200</td>
<td>336</td>
<td>2</td>
<td>45</td>
</tr>
<tr class="odd">
<td>Road-150 Red, 52</td>
<td>1080637.5400</td>
<td>302</td>
<td>3</td>
<td>49</td>
</tr>
<tr class="even">
<td>Road-150 Red, 56</td>
<td>1055589.6500</td>
<td>295</td>
<td>4</td>
<td>51</td>
</tr>
<tr class="odd">
<td>Road-150 Red, 44</td>
<td>1005493.8700</td>
<td>281</td>
<td>5</td>
<td>52</td>
</tr>
<tr class="even">
<td>Mountain-200 Black, 42</td>
<td>979960.7300</td>
<td>427</td>
<td>6</td>
<td>28</td>
</tr>
<tr class="odd">
<td>Mountain-200 Silver, 38</td>
<td>979035.7800</td>
<td>422</td>
<td>7</td>
<td>29</td>
</tr>
<tr class="even">
<td>Mountain-200 Black, 46</td>
<td>961600.8100</td>
<td>419</td>
<td>8</td>
<td>30</td>
</tr>
<tr class="odd">
<td>Mountain-200 Black, 38</td>
<td>954715.8400</td>
<td>416</td>
<td>9</td>
<td>31</td>
</tr>
<tr class="even">
<td>Mountain-200 Silver, 46</td>
<td>930315.9900</td>
<td>401</td>
<td>10</td>
<td>36</td>
</tr>
<tr class="odd">
<td>Sport-100 Helmet, Red</td>
<td>78027.7000</td>
<td>2230</td>
<td>68</td>
<td>5</td>
</tr>
<tr class="even">
<td>Sport-100 Helmet, Blue</td>
<td>74353.7500</td>
<td>2125</td>
<td>70</td>
<td>7</td>
</tr>
<tr class="odd">
<td>Sport-100 Helmet, Black</td>
<td>72954.1500</td>
<td>2085</td>
<td>71</td>
<td>9</td>
</tr>
<tr class="even">
<td>Fender Set - Mountain</td>
<td>46619.5800</td>
<td>2121</td>
<td>79</td>
<td>8</td>
</tr>
<tr class="odd">
<td>Water Bottle - 30 oz.</td>
<td>21177.5600</td>
<td>4244</td>
<td>129</td>
<td>1</td>
</tr>
<tr class="even">
<td>Mountain Bottle Cage</td>
<td>20229.7500</td>
<td>2025</td>
<td>131</td>
<td>10</td>
</tr>
<tr class="odd">
<td>AWC Logo Cap</td>
<td>19688.1000</td>
<td>2190</td>
<td>133</td>
<td>6</td>
</tr>
<tr class="even">
<td>Mountain Tire Tube</td>
<td>15444.0500</td>
<td>3095</td>
<td>136</td>
<td>3</td>
</tr>
<tr class="odd">
<td>Road Tire Tube</td>
<td>9480.2400</td>
<td>2376</td>
<td>153</td>
<td>4</td>
</tr>
<tr class="even">
<td>Patch Kit/8 Patches</td>
<td>7307.3900</td>
<td>3191</td>
<td>155</td>
<td>2</td>
</tr>
</tbody>
</table>
<p><strong>Insights:</strong> The analysis revealed the following insights:</p>
<ul>
<li>There is a strong disparity between high value and high volume products. The top 10 high value products are predominantly bikes, which have high revenue but relatively lower quantities sold. In contrast, the top 10 high volume products are mostly accessories, which have lower revenue but significantly higher quantities sold.</li>
<li>The high value products, such as the “Road-150 Red” series and “Mountain-200” series, generate substantial revenue but are sold in smaller quantities, indicating that they are likely premium products with higher price points. These products may require targeted marketing strategies to maintain their profitability while potentially increasing their sales volume.</li>
<li>The high volume products, such as the “Sport-100 Helmet” and “Water Bottle - 30 oz.,” sell in large quantities but contribute less to total revenue, suggesting that they may be more price-sensitive and could benefit from strategies focused on cost reduction or bundling to enhance their profitability.</li>
<li>The disparity between high value and high volume products highlights the importance of balancing our product portfolio to maximize overall profitability. While high value products can drive significant revenue, high volume products can contribute to steady cash flow and customer engagement. Therefore, it’s crucial to analyze both categories and develop strategies that leverage the strengths of each to optimize our product offerings and marketing efforts.<br>
We can use some optimization algorithms to find the optimal price points for high volume products to increase their revenue without significantly reducing their sales quantity. For example, as the control and automation engineering background I can build a linear programming model to determine the optimal price for each high volume product, taking into account factors such as production costs, demand elasticity, and competitive pricing. By optimizing the pricing strategy for high volume products, we can potentially increase their revenue contribution while maintaining or even boosting their sales quantity, ultimately enhancing overall profitability.</li>
</ul>
</section>
<section id="basket-size-analysis" class="level2">
<h2 class="anchored" data-anchor-id="basket-size-analysis">Basket Size Analysis</h2>
<p><code>13. What is our basket size distribution, and how frequently do customers buy multiple items in a single transaction?</code></p>
<p><strong>Solution Method:</strong> First of all we need to define the unique basket sizes. Basket size means the number of items purchased in a single transaction. To calculate this, we should group the sales data by <code>SalesOrderNumber</code> which represents a unique transaction and then count the total quantity of items in that single transaction. The results will give us all unique transactions and corresponding basket sizes. However, we need to define the number transactions for each basket size. Therefore, we should group by the obtained resutls based on the basket size and then count the number of transactions for each basket size. Finally, we can calculate the percentage of transactions for each basket size to understand how frequently customers buy multiple items in a single transaction. This analysis will provide insights into customer purchasing behavior and help us identify opportunities to encourage larger basket sizes through marketing strategies or promotions.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">with</span> bucket_size_calc <span class="kw">as</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">select</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>        <span class="co">-- first determine bucket size</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        SalesOrderNumber, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(OrderQuantity) <span class="kw">as</span> num_items</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">from</span> FactInternetSales</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">group</span> <span class="kw">by</span> SalesOrderNumber</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span> </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    num_items <span class="kw">as</span> bucket_size, </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(SalesOrderNumber) <span class="kw">as</span> num_orders,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cast</span>(<span class="fl">100.0</span> <span class="op">*</span> <span class="fu">count</span>(SalesOrderNumber) <span class="op">/</span> <span class="fu">sum</span>(<span class="fu">count</span>(SalesOrderNumber)) <span class="kw">over</span>()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>        <span class="kw">as</span> <span class="dt">decimal</span>(<span class="dv">6</span>,<span class="dv">3</span>)) <span class="kw">as</span> order_pct</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> bucket_size_calc</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="kw">group</span> <span class="kw">by</span> </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    num_items </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="kw">by</span> num_orders ;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>bucket_size</th>
<th>num_orders</th>
<th>order_pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>3</td>
<td>0.011</td>
</tr>
<tr class="even">
<td>7</td>
<td>12</td>
<td>0.043</td>
</tr>
<tr class="odd">
<td>6</td>
<td>109</td>
<td>0.394</td>
</tr>
<tr class="even">
<td>5</td>
<td>696</td>
<td>2.516</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3138</td>
<td>11.345</td>
</tr>
<tr class="even">
<td>3</td>
<td>5870</td>
<td>21.223</td>
</tr>
<tr class="odd">
<td>2</td>
<td>8163</td>
<td>29.513</td>
</tr>
<tr class="even">
<td>1</td>
<td>9668</td>
<td>34.954</td>
</tr>
</tbody>
</table>
<p><strong>Insights:</strong> The analysis revealed the following insights: - Most customers (34.954%) purchase a single item in a transaction, indicating that a significant portion of our sales comes from customers who buy one product at a time. This suggests that there may be opportunities to encourage customers to add more items to their baskets through targeted promotions or cross-selling strategies. - A substantial percentage of transactions (29.513%) involve customers purchasing two items, which indicates that there is already a significant level of multi-item purchasing behavior. This presents an opportunity to further increase the average basket size by promoting complementary products or offering discounts for purchasing multiple items. - The percentage of transactions decreases as the basket size increases, with only a small percentage of customers purchasing more than three items in a single transaction. This suggests that while there is some willingness among customers to purchase multiple items, there may be barriers to larger basket sizes that we can address through marketing strategies, such as offering bundled discounts or creating product packages that encourage customers to buy more items together. - Overall, understanding the basket size distribution provides valuable insights into customer purchasing behavior and can inform strategies to increase average order value and enhance customer engagement by encouraging larger basket sizes through targeted promotions and cross-selling opportunities.</p>
</section>
<section id="dead-weight-products" class="level2">
<h2 class="anchored" data-anchor-id="dead-weight-products">Dead Weight Products</h2>
<p><code>14. Are there any "Dead Weight" products in our active catalog that have negligible sales in the most recent year?</code></p>
<p><strong>Solution Method:</strong> To solve this question, we should calculate the financial metrics for each product in the most recent year by filtering the years in the join statements. Then we can identify products with negligible sales by setting thresholds for revenue and quantity. For example, we can consider products with total revenue less than $10,000 or total quantity sold less than 50 units as “Dead Weight” products. By analyzing these products, we can make informed decisions about whether to discontinue them or implement strategies to boost their sales, such as targeted marketing campaigns or bundling them with more popular products. This analysis will help us optimize our product catalog and focus on offerings that contribute more significantly to our overall profitability.</p>
<details>
<summary>
Show SQL Code
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    p.ProductKey,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    p.ProductName,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">sum</span>(fis.SalesAmount),<span class="dv">0</span>) <span class="kw">as</span> revenue,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">sum</span>(fis.OrderQuantity),<span class="dv">0</span>) <span class="kw">as</span> quantity</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> Products p</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="kw">left</span> <span class="kw">join</span> FactInternetSales fis</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">on</span> fis.ProductKey <span class="op">=</span> p.ProductKey</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">and</span> <span class="dt">year</span>(fis.OrderDate) <span class="op">=</span> <span class="dv">2013</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="kw">where</span> p.Status <span class="op">=</span> <span class="st">'Current'</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="kw">group</span> <span class="kw">by</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    p.ProductKey,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    p.ProductName</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="kw">having</span> </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">sum</span>(fis.SalesAmount),<span class="dv">0</span>) <span class="op">&lt;</span> <span class="dv">10000</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">or</span> </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">sum</span>(fis.OrderQuantity),<span class="dv">0</span>) <span class="op">&lt;</span> <span class="dv">50</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="kw">by</span> </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coalesce</span>(<span class="fu">sum</span>(fis.SalesAmount),<span class="dv">0</span>) <span class="kw">desc</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>ProductKey</th>
<th>ProductName</th>
<th>revenue</th>
<th>quantity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>570</td>
<td>Touring-3000 Yellow, 54</td>
<td>35632.8000</td>
<td>48</td>
</tr>
<tr class="even">
<td>586</td>
<td>Touring-3000 Blue, 50</td>
<td>35632.8000</td>
<td>48</td>
</tr>
<tr class="odd">
<td>571</td>
<td>Touring-3000 Yellow, 58</td>
<td>33405.7500</td>
<td>45</td>
</tr>
<tr class="even">
<td>595</td>
<td>Mountain-500 Silver, 52</td>
<td>27119.5200</td>
<td>48</td>
</tr>
<tr class="odd">
<td>597</td>
<td>Mountain-500 Black, 42</td>
<td>26459.5100</td>
<td>49</td>
</tr>
<tr class="even">
<td>591</td>
<td>Mountain-500 Silver, 40</td>
<td>25424.5500</td>
<td>45</td>
</tr>
<tr class="odd">
<td>592</td>
<td>Mountain-500 Silver, 42</td>
<td>25424.5500</td>
<td>45</td>
</tr>
<tr class="even">
<td>596</td>
<td>Mountain-500 Black, 40</td>
<td>25379.5300</td>
<td>47</td>
</tr>
<tr class="odd">
<td>600</td>
<td>Mountain-500 Black, 52</td>
<td>22139.5900</td>
<td>41</td>
</tr>
<tr class="even">
<td>593</td>
<td>Mountain-500 Silver, 44</td>
<td>21469.6200</td>
<td>38</td>
</tr>
<tr class="odd">
<td>529</td>
<td>Road Tire Tube</td>
<td>8869.7700</td>
<td>2223</td>
</tr>
<tr class="even">
<td>530</td>
<td>Touring Tire Tube</td>
<td>7000.9700</td>
<td>1403</td>
</tr>
<tr class="odd">
<td>480</td>
<td>Patch Kit/8 Patches</td>
<td>6929.5400</td>
<td>3026</td>
</tr>
<tr class="even">
<td>484</td>
<td>Bike Wash - Dissolver</td>
<td>6908.5500</td>
<td>869</td>
</tr>
<tr class="odd">
<td>481</td>
<td>Racing Socks, M</td>
<td>2526.1900</td>
<td>281</td>
</tr>
<tr class="even">
<td>482</td>
<td>Racing Socks, L</td>
<td>2337.4000</td>
<td>260</td>
</tr>
<tr class="odd">
<td>601</td>
<td>LL Bottom Bracket</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>602</td>
<td>ML Bottom Bracket</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>603</td>
<td>HL Bottom Bracket</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>531</td>
<td>LL Mountain Frame - Black, 42</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>532</td>
<td>LL Mountain Frame - Black, 44</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>533</td>
<td>LL Mountain Frame - Black, 48</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>534</td>
<td>LL Mountain Frame - Black, 52</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>542</td>
<td>LL Mountain Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>543</td>
<td>ML Mountain Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>544</td>
<td>HL Mountain Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>545</td>
<td>LL Road Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>546</td>
<td>ML Road Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>547</td>
<td>HL Road Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>548</td>
<td>Touring Pedal</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>549</td>
<td>ML Mountain Frame-W - Silver, 38</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>550</td>
<td>LL Mountain Frame - Black, 40</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>551</td>
<td>LL Mountain Frame - Silver, 40</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>552</td>
<td>Front Derailleur</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>553</td>
<td>LL Touring Handlebars</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>554</td>
<td>HL Touring Handlebars</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>555</td>
<td>Front Brakes</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>556</td>
<td>LL Crankset</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>557</td>
<td>ML Crankset</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>558</td>
<td>HL Crankset</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>559</td>
<td>Chain</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>492</td>
<td>HL Touring Frame - Yellow, 60</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>493</td>
<td>LL Touring Frame - Yellow, 62</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>494</td>
<td>HL Touring Frame - Yellow, 46</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>495</td>
<td>HL Touring Frame - Yellow, 50</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>496</td>
<td>HL Touring Frame - Yellow, 54</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>497</td>
<td>HL Touring Frame - Blue, 46</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>498</td>
<td>HL Touring Frame - Blue, 50</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>499</td>
<td>HL Touring Frame - Blue, 54</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>500</td>
<td>HL Touring Frame - Blue, 60</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>501</td>
<td>Rear Derailleur</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>502</td>
<td>LL Touring Frame - Blue, 50</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>503</td>
<td>LL Touring Frame - Blue, 54</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>504</td>
<td>LL Touring Frame - Blue, 58</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>505</td>
<td>LL Touring Frame - Blue, 62</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>506</td>
<td>LL Touring Frame - Yellow, 44</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>507</td>
<td>LL Touring Frame - Yellow, 50</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>508</td>
<td>LL Touring Frame - Yellow, 54</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>509</td>
<td>LL Touring Frame - Yellow, 58</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>510</td>
<td>LL Touring Frame - Blue, 44</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>511</td>
<td>ML Mountain Frame-W - Silver, 40</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>512</td>
<td>ML Mountain Frame-W - Silver, 42</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>513</td>
<td>ML Mountain Frame-W - Silver, 46</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>514</td>
<td>Rear Brakes</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>515</td>
<td>LL Mountain Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>516</td>
<td>ML Mountain Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>517</td>
<td>HL Mountain Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>518</td>
<td>LL Road Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>519</td>
<td>ML Road Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>520</td>
<td>HL Road Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>521</td>
<td>LL Touring Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>522</td>
<td>ML Touring Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>523</td>
<td>HL Touring Seat/Saddle</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>524</td>
<td>LL Mountain Frame - Silver, 42</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>525</td>
<td>LL Mountain Frame - Silver, 44</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>526</td>
<td>LL Mountain Frame - Silver, 48</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>527</td>
<td>LL Mountain Frame - Silver, 52</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>1</td>
<td>Adjustable Race</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Bearing Ball</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td>BB Ball Bearing</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Headset Ball Bearings</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td>Blade</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>6</td>
<td>LL Crankarm</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>7</td>
<td>ML Crankarm</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>8</td>
<td>HL Crankarm</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>9</td>
<td>Chainring Bolts</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>10</td>
<td>Chainring Nut</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>11</td>
<td>Chainring</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>12</td>
<td>Crown Race</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>13</td>
<td>Chain Stays</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>14</td>
<td>Decal 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>15</td>
<td>Decal 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>16</td>
<td>Down Tube</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>17</td>
<td>Mountain End Caps</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>18</td>
<td>Road End Caps</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>19</td>
<td>Touring End Caps</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>20</td>
<td>Fork End</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>21</td>
<td>Freewheel</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>22</td>
<td>Flat Washer 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>23</td>
<td>Flat Washer 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>24</td>
<td>Flat Washer 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>25</td>
<td>Flat Washer 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>26</td>
<td>Flat Washer 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>27</td>
<td>Flat Washer 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>28</td>
<td>Flat Washer 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>29</td>
<td>Flat Washer 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>30</td>
<td>Flat Washer 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>31</td>
<td>Fork Crown</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>32</td>
<td>Front Derailleur Cage</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>33</td>
<td>Front Derailleur Linkage</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>34</td>
<td>Guide Pulley</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>35</td>
<td>LL Grip Tape</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>36</td>
<td>ML Grip Tape</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>37</td>
<td>HL Grip Tape</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>38</td>
<td>Thin-Jam Hex Nut 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>39</td>
<td>Thin-Jam Hex Nut 10</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>40</td>
<td>Thin-Jam Hex Nut 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>41</td>
<td>Thin-Jam Hex Nut 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>42</td>
<td>Thin-Jam Hex Nut 15</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>43</td>
<td>Thin-Jam Hex Nut 16</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>44</td>
<td>Thin-Jam Hex Nut 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>45</td>
<td>Thin-Jam Hex Nut 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>46</td>
<td>Thin-Jam Hex Nut 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>47</td>
<td>Thin-Jam Hex Nut 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>48</td>
<td>Thin-Jam Hex Nut 13</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>49</td>
<td>Thin-Jam Hex Nut 14</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>50</td>
<td>Thin-Jam Hex Nut 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>51</td>
<td>Thin-Jam Hex Nut 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>52</td>
<td>Thin-Jam Hex Nut 12</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>53</td>
<td>Thin-Jam Hex Nut 11</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>54</td>
<td>Hex Nut 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>55</td>
<td>Hex Nut 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>56</td>
<td>Hex Nut 16</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>57</td>
<td>Hex Nut 17</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>58</td>
<td>Hex Nut 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>59</td>
<td>Hex Nut 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>60</td>
<td>Hex Nut 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>61</td>
<td>Hex Nut 22</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>62</td>
<td>Hex Nut 23</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>63</td>
<td>Hex Nut 12</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>64</td>
<td>Hex Nut 13</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>65</td>
<td>Hex Nut 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>66</td>
<td>Hex Nut 10</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>67</td>
<td>Hex Nut 11</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>68</td>
<td>Hex Nut 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>69</td>
<td>Hex Nut 20</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>70</td>
<td>Hex Nut 21</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>71</td>
<td>Hex Nut 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>72</td>
<td>Hex Nut 14</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>73</td>
<td>Hex Nut 15</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>74</td>
<td>Hex Nut 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>75</td>
<td>Hex Nut 18</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>76</td>
<td>Hex Nut 19</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>77</td>
<td>Handlebar Tube</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>78</td>
<td>Head Tube</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>79</td>
<td>LL Hub</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>80</td>
<td>HL Hub</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>81</td>
<td>Keyed Washer</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>82</td>
<td>External Lock Washer 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>83</td>
<td>External Lock Washer 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>84</td>
<td>External Lock Washer 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>85</td>
<td>External Lock Washer 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>86</td>
<td>External Lock Washer 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>87</td>
<td>External Lock Washer 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>88</td>
<td>External Lock Washer 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>89</td>
<td>External Lock Washer 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>90</td>
<td>External Lock Washer 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>91</td>
<td>Internal Lock Washer 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>92</td>
<td>Internal Lock Washer 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>93</td>
<td>Internal Lock Washer 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>94</td>
<td>Internal Lock Washer 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>95</td>
<td>Internal Lock Washer 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>96</td>
<td>Internal Lock Washer 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>97</td>
<td>Internal Lock Washer 10</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>98</td>
<td>Internal Lock Washer 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>99</td>
<td>Internal Lock Washer 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>100</td>
<td>Internal Lock Washer 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>101</td>
<td>Thin-Jam Lock Nut 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>102</td>
<td>Thin-Jam Lock Nut 10</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>103</td>
<td>Thin-Jam Lock Nut 1</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>104</td>
<td>Thin-Jam Lock Nut 2</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>105</td>
<td>Thin-Jam Lock Nut 15</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>106</td>
<td>Thin-Jam Lock Nut 16</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>107</td>
<td>Thin-Jam Lock Nut 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>108</td>
<td>Thin-Jam Lock Nut 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>109</td>
<td>Thin-Jam Lock Nut 3</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>110</td>
<td>Thin-Jam Lock Nut 4</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>111</td>
<td>Thin-Jam Lock Nut 13</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>112</td>
<td>Thin-Jam Lock Nut 14</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>113</td>
<td>Thin-Jam Lock Nut 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>114</td>
<td>Thin-Jam Lock Nut 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>115</td>
<td>Thin-Jam Lock Nut 12</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>116</td>
<td>Thin-Jam Lock Nut 11</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>117</td>
<td>Lock Nut 5</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>118</td>
<td>Lock Nut 6</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>119</td>
<td>Lock Nut 16</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>120</td>
<td>Lock Nut 17</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>121</td>
<td>Lock Nut 7</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="odd">
<td>122</td>
<td>Lock Nut 8</td>
<td>0.0000</td>
<td>0</td>
</tr>
<tr class="even">
<td>123</td>
<td>Lock Nut 9</td>
<td>0.0000</td>
<td>0</td>
</tr>
</tbody>
</table>
<p><strong>Insights:</strong> The analysis revealed the following insights: - Some of dead weigt products have significant revenue but low quantity sold, such as “Touring-3000 Yellow, 54” and “Mountain-500 Silver, 52”. These products may be considered for reevaluation in the product lineup, as they may not be contributing significantly to overall profitability despite generating some revenue. It may be worth exploring strategies to boost their sales or considering discontinuation if they are not aligned with our business goals. - A large number of products have zero revenue and zero quantity sold, indicating that they are not purchased at all. These products may be candidates for removal from the active catalog, as they are not contributing to sales and may be taking up valuable inventory space. It’s important to regularly review and optimize the product catalog to focus on offerings that are more likely to drive profitability and meet customer demand.</p>
</details></section>
<section id="product-pricing-tiers-effect" class="level2">
<h2 class="anchored" data-anchor-id="product-pricing-tiers-effect">Product Pricing Tiers Effect</h2>
<p><code>15. How does product pricing tier affect consumer purchasing behavior?</code></p>
<p><strong>Solution Method:</strong> To solve this question, we can categorize products into different pricing tiers based on their list price. For example, we can define “Entry-level” products as those with a list price of $100 or less, “Standard” products as those with a list price between $100 and $1000, and “Premium” products as those with a list price above $1000. Then we can analyze the total revenue, total quantity sold, and the percentage of total revenue for each pricing tier to understand how consumer purchasing behavior varies across different price points. This analysis will provide insights into which pricing tiers are more popular among customers and how they contribute to overall sales, allowing us to make informed decisions about product pricing strategies and inventory management.</p>
<details>
<summary>
Show SQL code
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">min</span>(ListPrice) <span class="kw">as</span> min_price,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">avg</span>(ListPrice) <span class="kw">as</span> avg_price,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">max</span>(ListPrice) <span class="kw">as</span> max_price,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    STDEV(ListPrice) <span class="kw">as</span> std</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> products;</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">-- min price : 2.28</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">-- avg price : 747.6617</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">-- max price : 3578.27</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="kw">with</span> product_stats <span class="kw">as</span> (</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">select</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        p.ProductKey,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        p.ListPrice,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(fis.SalesAmount) <span class="kw">as</span> revenue,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(fis.OrderQuantity) <span class="kw">as</span> quantity</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="kw">from</span> Products p </span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">left</span> <span class="kw">join</span> FactInternetSales fis</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        <span class="kw">on</span> fis.ProductKey <span class="op">=</span> p.ProductKey</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="kw">group</span> <span class="kw">by</span> </span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        p.ProductKey,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        p.ListPrice</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="kw">select</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">case</span> </span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">when</span> ListPrice <span class="op">&lt;=</span> <span class="dv">100</span> <span class="cf">then</span> <span class="st">'Entry-level'</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">when</span> ListPrice <span class="op">&gt;</span> <span class="dv">1000</span> <span class="cf">then</span> <span class="st">'Premium'</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span> <span class="st">'Standard'</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">end</span> <span class="kw">as</span> <span class="st">'Price-Tiers'</span>,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(revenue) <span class="kw">as</span> total_revenue,</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(quantity) <span class="kw">as</span> total_units_sold,</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cast</span>(<span class="fl">100.0</span> <span class="op">*</span> <span class="fu">sum</span>(revenue) <span class="op">/</span> <span class="fu">nullif</span>(<span class="fu">sum</span>(<span class="fu">sum</span>(revenue)) <span class="kw">over</span> (),<span class="dv">0</span>) </span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>        <span class="kw">as</span> <span class="dt">decimal</span>(<span class="dv">10</span>,<span class="dv">3</span>))<span class="kw">as</span> revenue_pct</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="kw">from</span> product_stats</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="kw">group</span> <span class="kw">by</span> </span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">case</span> </span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>        <span class="cf">when</span> ListPrice <span class="op">&lt;=</span> <span class="dv">100</span> <span class="cf">then</span> <span class="st">'Entry-level'</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">when</span> ListPrice <span class="op">&gt;</span> <span class="dv">1000</span> <span class="cf">then</span> <span class="st">'Premium'</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span> <span class="st">'Standard'</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">end</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="kw">order</span> <span class="kw">by</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    revenue_pct <span class="kw">desc</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<p><strong>Results:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Price-Tiers</th>
<th>total_revenue</th>
<th>total_units_sold</th>
<th>revenue_pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Premium</td>
<td>25810527.2969</td>
<td>11348</td>
<td>87.914</td>
</tr>
<tr class="even">
<td>Standard</td>
<td>2586568.3538</td>
<td>4434</td>
<td>8.810</td>
</tr>
<tr class="odd">
<td>Entry-level</td>
<td>961581.5700</td>
<td>44616</td>
<td>3.275</td>
</tr>
</tbody>
</table>
<p><strong>Insights:</strong> The analysis revealed the following insights: - The “Premium” pricing tier generates the majority of total revenue (87.914%) despite having the lowest total units sold (11,348). This indicates that customers are willing to pay a premium price for high-value products, which suggests that there is a strong demand for premium offerings in our product catalog. This insight can inform our pricing strategy, as we may want to focus on promoting and expanding our premium product offerings to capitalize on this demand and maximize profitability. - The “Standard” pricing tier contributes a smaller portion of total revenue (8.810%) with a moderate number of units sold (4,434). This suggests that while there is some demand for standard-priced products, they may not be as popular as premium products. We may want to evaluate our standard product offerings and consider strategies to enhance their appeal, such as improving product features, offering promotions, or bundling them with premium products to increase their attractiveness to customers. - The “Entry-level” pricing tier generates the least total revenue (3.275%) despite having the highest total units sold (44,616). This indicates that while entry-level products are popular among customers, they may not be contributing significantly to overall profitability due to their lower price points. We may want to explore strategies to increase the profitability of entry-level products, such as optimizing production costs, offering value-added services, or creating bundles that include entry-level products with higher-priced items to encourage customers to spend more.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this section, we conducted a comprehensive analysis of our product catalog, focusing on various aspects such as profitability, sales performance, customer purchasing behavior, and product pricing strategies. We defined the profit margins for the products and identified the most profitable product categories, as well as the disparity between high volume and high value products. We also analyzed the basket size distribution to understand how frequently customers buy multiple items in a single transaction and identified “Dead Weight” products that have negligible sales. Finally, we examined how product pricing tiers affect consumer purchasing behavior. Overall, these insights provide valuable information that can inform our inventory management, marketing strategies, and product development efforts to optimize profitability and meet customer demand effectively. By leveraging this analysis, we can make data-driven decisions to enhance our product offerings and drive business growth.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>